/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        iPhone phone2 = new iPhone("iPhone 7", "Green", "iPhone");
        phone2.call("test");
        Android phone3 = new Android ("S10", "Green", "Android");

        phone2.mobileInfo();
        phone3.mobileInfo();

        Person name = new Person();
        name.setName("Kenneth");
        name.setMobile(phone3);
        name.makeACall("Test message");

        iPhoneRobot iRobot = new iPhoneRobot();
        iRobot.setMobile(phone2);
        iRobot.checkMobile();
        iRobot.setMobile(phone3);
        iRobot.checkMobile();
    }
}
